# Generated by Django 5.2.7 on 2025-10-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('processing', 'processing'), ('done', 'done'), ('failed', 'failed')], default='pending', max_length=16)),
                ('original', models.FileField(upload_to='uploads/')),
                ('outputs', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True, default='')),
            ],
        ),
    ]
